replicaCount: 1
image:
  repository: ubuntu
  tag: ""
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 128Mi
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
